--------------------------------------------------------
--  File created - Monday-June-16-2025   
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE PROCEDURE "BONUS"."SP_AITEST" 
   (P_BD                          REPS.BD%TYPE
   ,P_REP_NUMBER                  RDS.REP_NUMBER%TYPE
   ,P_TERM_STOP_PAYMENT_DATE      REPS_STATUS.TERM_STOP_PAYMENT_DATE%TYPE
   ,P_USER                        AUTH_USERS.USER_ID%TYPE
   ) IS

   CURSOR RDS_TERM_REP IS
   SELECT RS.TERM_VESTED_IND
	 FROM REPS_NUMBERS RN,REPS_STATUS RS
    WHERE RN.BD=P_BD
      AND RN.REP_NUMBER = P_REP_NUMBER
      AND RN.PRIMARY_SSN_IND = 'Y'
	  AND RN.SSN = RS.SSN
	  AND RN.BD = RS.BD
	  ORDER BY TERM_VESTED_IND;


  V_VESTED_IND          REPS_STATUS.TERM_VESTED_IND%TYPE;

BEGIN
   OPEN  RDS_TERM_REP;
   FETCH RDS_TERM_REP INTO V_VESTED_IND;
   CLOSE RDS_TERM_REP;

  IF V_VESTED_IND = 'Y' THEN

  	 	  --Changed NIIT 10/15/2007 Issue #813
	  -- TERMINATE SET TERM DATE FOR RDS RECORDS

      UPDATE RDS
        SET EFFECTIVE_TO_DATE = P_TERM_STOP_PAYMENT_DATE
		   ,LAST_MOD_ID = P_USER
      WHERE  BD = P_BD
         	 AND REP_NUMBER= P_REP_NUMBER
         	 AND (EFFECTIVE_TO_DATE IS NULL
                OR EFFECTIVE_TO_DATE > P_TERM_STOP_PAYMENT_DATE);

   --ADDED NIIT 10/15/2007 Issue #813
	   --Revert term date for RDS for RDS GROUP Containing 'F' for vested reps

		UPDATE RDS
        SET EFFECTIVE_TO_DATE = NULL
		WHERE
			 BD = P_BD
         	 AND REP_NUMBER= P_REP_NUMBER
			 AND EFFECTIVE_TO_DATE = P_TERM_STOP_PAYMENT_DATE
			 AND LAST_MOD_ID = 'TERMRDS'
			 AND  EXISTS (SELECT 1
						   FROM RDS_GROUPS_TO_PROD_GROUPS RG
						 WHERE RG.BD  = P_BD
						 	  AND RG.PROD_GROUP_CODE = 'F'
							  AND RG.RDS_GROUP_CODE = RDS.APPLIES_TO_RDS_GROUP);

	   --ADDED NIIT 10/15/2007 Issue #813
	   --Revert term date for RDS for PRODUCT GROUP Containing 'F' for Vested reps

		UPDATE RDS
        SET EFFECTIVE_TO_DATE = NULL
		WHERE
			 BD = P_BD
         	 AND REP_NUMBER= P_REP_NUMBER
			 AND EFFECTIVE_TO_DATE = P_TERM_STOP_PAYMENT_DATE
			 AND LAST_MOD_ID = 'TERMRDS'
			 AND  RDS.APPLIES_TO_PROD_GROUP= 'F';

		   --ADDED NIIT 10/15/2007 Issue #813
	   --Revert term date for RDS for Sponsors selling FI products for Vested reps

		UPDATE RDS
        SET EFFECTIVE_TO_DATE = NULL
		WHERE
			 BD = P_BD
         	 AND REP_NUMBER= P_REP_NUMBER
			 AND EFFECTIVE_TO_DATE = P_TERM_STOP_PAYMENT_DATE
			 AND LAST_MOD_ID = 'TERMRDS'
			 AND  EXISTS (SELECT 1
			   	 		   FROM SPONSORS
				 		   WHERE SPON_CODE = RDS.APPLIES_TO_SPON_CODE
						   		 AND SPONSORS.GROUP_CODE = 'F');

	    --ADDED NIIT 10/15/2007 Issue #813
	   --Revert term date for RDS for Sponsors selling FI products for Vested reps

		UPDATE RDS
        SET EFFECTIVE_TO_DATE = NULL
		WHERE
			 BD = P_BD
         	 AND REP_NUMBER= P_REP_NUMBER
			 AND EFFECTIVE_TO_DATE = P_TERM_STOP_PAYMENT_DATE
			 AND LAST_MOD_ID = 'TERMRDS'
			 AND  EXISTS (SELECT 1
                           FROM PRODUCTS P
						   WHERE RDS.APPLIES_TO_PRODUCT_NUMBER = P.PRODUCT_NUMBER
                                 AND  P.GROUP_CODE = 'F');

		    --ADDED NIIT 10/15/2007 Issue #813
	   --Set status_ind for RDS to 60

		UPDATE RDS
        SET STATUS_IND = 60
			,LAST_MOD_DATE = SYSDATE
           ,LAST_MOD_ID = P_USER
		WHERE
			 BD = P_BD
         	 AND REP_NUMBER= P_REP_NUMBER
			 AND EFFECTIVE_TO_DATE = P_TERM_STOP_PAYMENT_DATE
       AND REP_NUMBER NOT IN (SELECT R1.REP_NUMBER FROM BONUS.REPS_NUMBERS R1 WHERE R1.STATUS_IND = 10 AND R1.REP_NUMBER = P_REP_NUMBER) --By Balaji - 27-MAY-2016- BNS-76055
			 AND LAST_MOD_ID = 'TERMRDS';



  ELSE
	    UPDATE RDS
        SET STATUS_IND = 60
           ,EFFECTIVE_TO_DATE = P_TERM_STOP_PAYMENT_DATE
           ,LAST_MOD_DATE = SYSDATE
           ,LAST_MOD_ID = P_USER
   		 WHERE
		 	   BD = P_BD
         	   AND REP_NUMBER= P_REP_NUMBER
             AND REP_NUMBER NOT IN (SELECT R1.REP_NUMBER FROM BONUS.REPS_NUMBERS R1 WHERE R1.STATUS_IND = 10 AND R1.REP_NUMBER = P_REP_NUMBER) --By Balaji - 27-MAY-2016- BNS-76055
         	   AND (EFFECTIVE_TO_DATE IS NULL
               OR EFFECTIVE_TO_DATE > P_TERM_STOP_PAYMENT_DATE);
	END IF;
END;

/
